import type { ReactNode, RefObject } from "react"
import React from "react"
import { createRoot, type Root } from "react-dom/client"

export class ShadowBoundaryElement extends HTMLElement {
    private static instances: ShadowBoundaryElement[] = []
    private static styles: string[] = []

    private root: Root | null = null

    // these are generated by a vite plugin
    static injectStyles(cssCode: string) {
        ShadowBoundaryElement.styles.push(cssCode)
        ShadowBoundaryElement.instances.forEach(instance => {
            const stylesheet = new CSSStyleSheet()
            stylesheet.replaceSync(cssCode)
            instance.shadowRoot?.adoptedStyleSheets.push(stylesheet)
        })
    }

    constructor() {
        super()
        ShadowBoundaryElement.instances.push(this)
    }

    connectedCallback() {
        if(!this.shadowRoot) {
            const shadow = this.attachShadow({ mode: 'open' })
            ShadowBoundaryElement.styles.forEach(cssCode => {
                const stylesheet = new CSSStyleSheet()
                stylesheet.replaceSync(cssCode)
                shadow.adoptedStyleSheets.push(stylesheet)
            })
        } else {
            this.shadowRoot.innerHTML = ''
        }  
        
        this.root = createRoot(this.shadowRoot!)
    }

    render(node: ReactNode) {
        this.root.render(node)
    }
}

export function ensureDefined() {
    if(!customElements.get('reunionpage-shadow-boundary')) {
        customElements.define('reunionpage-shadow-boundary', ShadowBoundaryElement)
    }
}

export const ShadowBoundary: React.FC<{ ref: RefObject<ShadowBoundaryElement | null> }> = ({ ref }) => {
    return <>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Martian+Mono:wght@100..800&family=Spline+Sans:wght@300..700&display=swap" rel="stylesheet" />
        <reunionpage-shadow-boundary
            style={{ display: 'block', height: '100%', backgroundColor: '#1f2325' }}
            ref={ref}
        />
    </>
}